
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-yaml

  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.0.0 
    hooks:
      - id: mix-format
